version: "3.9"

services:
  getRedditImages:
    build: ./getRedditImages
    restart: always
    links:
      - "db:db"
  db:
    build: ./db
    restart: always
  uploadInstaImages:
    build: ./uploadInstaImages
    restart: always
    links:
      - "db:db"