version: "3.9"

services:
  get_reddit_images:
    build: ./getRedditImages
    restart: always
    links:
      - "db:db"
    volumes:
      - images:/usr/src/app/images
    environment:
      - PYTHONUNBUFFERED=1
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DATABASE=${POSTGRES_DB}
      - IMG_DIR=/usr/src/app/images
      - DB_PORT=5432
    env_file:
      - .envReddit
    depends_on:
      - db
  db:
    build: ./db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
  upload_insta_images:
    build: ./uploadInstaImages
    restart: always
    environment:
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDATABASE=${POSTGRES_DB}
      - PGHOST=db
      - PGPORT=5432
volumes:
  images:
  db-data:
